name: gherkin_gen
description: Command-line tool to generate Step classes from feature files.
# version: 1.0.0
# homepage: https://www.example.com
# author: Allan Davis <cajun.code@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'


dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0

dependencies:
  gherkin: ^1.0.4
